name: InstaTnT
main: me.TheEpicButterStudios.InstaTnT.InstaTnT
version: 1.1
author: TheEpicButterStudios
commands:
   instaboom:
      description: Enable InstaTnT.
permissions:
   instatnt.reload.full:
      description: Allows you to run /instaboom reload full
      default: op
   instatnt.all:
      description: Allows access to everything.
      default: op